site_name: Komm
site_url: https://komm.dev/
repo_url: https://github.com/rwnobrega/komm/

docs_dir: site/docs
site_dir: site/build

watch:
  - src/komm/
  - site/

extra_css:
  - css/katex.css
  - css/markdown.css
  - css/mkdocs.css
  - css/mkdocstrings.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js

validation:
  links:
    absolute_links: ignore
    unrecognized_links: ignore

plugins:
  - search
  - gen-files:
      scripts:
        - site/gen_pages.py
  - literate-nav:
      nav_file: nav.md
      tab_length: 2
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - mkdocstrings:
      custom_templates: site/templates
      handlers:
        python:
          options:
            show_bases: false
            # show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
            docstring_section_style: list
            members_order: source
            group_by_category: false
            show_signature: false
            extensions:
              - griffe_inherited_docstrings:
                  merge: true

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - navigation.footer
    # - toc.integrate
    - hide:
        - navigation

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - site/includes/acronyms.md
        - site/includes/bibliography.md
  - tables
