[project]
name = "komm"
authors = [{ name = "Roberto W. Nobrega", email = "rwnobrega@gmail.com" }]
description = "An open-source library for Python 3 providing tools for analysis and simulation of analog and digital communication systems."
readme = "README.md"
urls = { home = "https://komm.dev/", repository = "https://github.com/rwnobrega/komm/" }
license = { file = "LICENSE" }
version = "0.8.0"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel", "numpy", "scipy"]

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
addopts = "--doctest-modules"
python_files = "test_*.py"
python_functions = "test_*"
pythonpath = "."
testpaths = ["komm", "tests"]
