[project]
authors = [{name = "Roberto W. Nobrega", email = "rwnobrega@gmail.com"}]
description = "An open-source library for Python 3 providing tools for analysis and simulation of analog and digital communication systems."
documentation = "https://komm.dev/docs/"
homepage = "https://komm.dev/"
license = "GPL"
name = "komm"
readme = "README.md"
repository = "https://github.com/rwnobrega/komm"
version = "0.8.0"

[project.urls]
Documentation = "https://komm.dev/docs/"
Source = "https://github.com/rwnobrega/komm/"

[project.packages]
exclude = ["contrib", "docs", "tests*"]

[build-system]
python_requires = ">=3.8"
requires = ["setuptools", "wheel", "numpy", "scipy"]

[tool.pytest.ini_options]
addopts = "--doctest-modules"
python_files = "test_*.py"
python_functions = "test_*"
pythonpath = "."
testpaths = ["komm", "tests"]
