[project]
name = "komm"
version = "0.8.2"
description = "An open-source library for Python 3 providing tools for analysis and simulation of analog and digital communication systems."
readme = "README.md"
authors = [{ name = "Roberto W. Nobrega", email = "rwnobrega@gmail.com" }]
license = { text = "GPL-3.0-only" }
dependencies = [
    "attrs>=23.1.0",
    "numpy>=1.24.4",
    "scipy>=1.9.3",
]
requires-python = ">=3.8"
urls = { home = "https://komm.dev/", repository = "https://github.com/rwnobrega/komm/" }

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
python_files = ["test_*.py", "bench_*.py"]
python_functions = ["test_*", "bench_*"]
pythonpath = "."
testpaths = ["src/komm", "tests", "benchmarks"]

[tool.pdm.dev-dependencies]
lint = [
    "black>=23.7.0",
    "isort>=5.12.0",
]
test = [
    "pytest>=7.4.0",
    "pytest-benchmark>=4.0.0",
]
doc = [
    "mkdocs>=1.4.3",
    "mkdocs-material>=9.1.18",
    "mkdocstrings>=0.22.0",
    "mkdocstrings-python>=1.1.2",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-include-markdown-plugin>=3.9.1",
    "mkdocs-literate-nav>=0.6.0",
]
debug = [
    "ipykernel>=6.24.0",
    "matplotlib>=3.7.2",
]
