name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e ".[lint,test]"
      - name: Force NumPy version for type checking
        run: pip install numpy==2.3
      - name: Black
        run: black --check .
      - name: Flake8
        run: flake8 src/
      - name: Basedpyright
        run: basedpyright
      - name: pytest
        run: pytest
