name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install komm
        run: |
          pip install -e .
      - name: Check code style
        run: |
          pip install black
          black --check .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest
